version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  webapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
        PORT: "3000"
        RACK_ENV: "production"
        DATABASE_URL: "postgres://postgres:example@db:5432/postgres"
        LOG_LEVEL: "${LOG_LEVEL}"
        LOG_URL: "${LOG_URL}"


    depends_on:
      - db