openapi: 3.0.0
info:
  title: Web Template
  description: A simple template for web applications
  version: 1.0.0
servers:
  - url: <server_url>
  - url: otracosa
paths:
  /:
    get:
      summary: Classic hello world
      responses:
        '200':
          description: Just a "Hello People" string

    post:
        summary: POST example
        responses:
          '200':
            description: Successful result
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/SuccessfulResult'
          '404':
            description: Resource not found

  /post_with_body:
    post:
      summary: POST with body example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyExample'
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulResult'
          '404':
            description: Resource not found
components:
  schemas:
    SuccessfulResult:
      properties:
        name:
          type: string
        value:
          type: integer

    BodyExample:
      properties:
        name:
          type: string
        value:
          type: integer
        a_list:
          type: array
          items:
            $ref: '#/components/schemas/BodyItemExample'

    BodyItemExample:
      properties:
        id:
          type: string
        quantity:
          type: integer
